version: '3.8'

networks:
  prova-usuarios:

volumes:
  prova-usuarios-keycloak-data:
  prova-usuarios-keycloak_logs:


services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command:
      - start-dev
    volumes:
      - prova-usuarios-keycloak-data:/opt/jboss/keycloak/standalone/data
      - prova-usuarios-keycloak_logs:/opt/jboss/keycloak/standalone/log

#  app:
#    container_name: app_usuarios
#    image: constrsw-2024-1/oauth
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        JAR_FILE: ./target
#    environment:
#      - ?
#    ports:
#      - 8081:8081
#    networks:
#      - prova-usuarios
#    depends_on:
#      - keycloak