version: '3.9'

networks:
  prova-usuarios:

volumes:
  prova-usuarios-keycloak-data:
  prova-usuarios-keycloak_logs:

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command:
      - start-dev
    volumes:
      - prova-usuarios-keycloak-data:/opt/jboss/keycloak/standalone/data
      - prova-usuarios-keycloak_logs:/opt/jboss/keycloak/standalone/log

#  app:
#    container_name: app-prova-usuarios
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/provaAttus
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - 8081:8081

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=provaAttus
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data